name: Build Advanced Installer Project (.AIP) Demo
on: [workflow_dispatch]
jobs:
  advinst-aip-build-demo:
    runs-on: windows-latest
    name: Build Aip Demo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build AIP
        uses: caphyon/advinst-github-action@v2.0
        with:
          advinst-version: '20.7.1'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\TestForGA.aip
          aip-build-name: DefaultBuild
          aip-package-name: setup.msi
          aip-output-dir:  ${{ github.workspace }}\setup
          aip-commands: |
            SetProperty FOO="foo"
            SetVersion 1.3.0
      - name: Publish setup artifact
        uses: actions/upload-artifact@v4
        with:
          name: setup
          path: ${{ github.workspace }}\setup\setup.msi
      - name: Release
        if: ${{ success() }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test AdvancedInstaller with GithubActions
          tag_name: 1.3.0
          make_latest: ${{ inputs.make_latest }}
          prerelease: ${{ inputs.prerelease }}
          files: ${{ github.workspace }}\setup\setup.msi
